// Code generated by protoc-gen-wzo-errno. DO NOT EDIT.
// versions:
//   - protoc-gen-wzo-errno 0.1.0
//   - protoc                 v3.17.3
// source: errno.proto

package errno

import (
	errors "github.com/wyy-go/wzo/core/errors"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = errors.New

func ErrInternalServer(opts ...errors.Option) *errors.Error {
	return errors.New(500, "服务器错误", opts...)
}
func ErrBadRequest(opts ...errors.Option) *errors.Error {
	return errors.New(400, "请求参数错误", opts...)
}
func ErrTimeout(opts ...errors.Option) *errors.Error {
	return errors.New(1000, "操作超时", opts...)
}
func ErrCustom(opts ...errors.Option) *errors.Error {
	return errors.New(1001, "自定义错误", opts...)
}
func ErrBizError(opts ...errors.Option) *errors.Error {
	return errors.New(1002, "业务错误", opts...)
}
func ErrUserOrPasswordIncorrect(opts ...errors.Option) *errors.Error {
	return errors.New(1003, "用户名或密码错误", opts...)
}
